title = "Alec Lowry"
description = "Personal website"
base_url = "https://aleclowry.com"

default_language = "en"

compile_sass = false
build_search_index = false
minify_html = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
external_links_target_blank = true
external_links_no_referrer = true

[extra]
author = "Alec Lowry"
